export interface Recipe {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  cookTime: string;
  prepTime: string;
  servings: number;
  rating: number;
  tags: string[];
  image: string;
  ingredients: string[];
  instructions: string[];
}

export const recipes: Recipe[] = [
  {
    slug: "rainbow-buddha-bowl",
    title: "Rainbow Buddha Bowl",
    excerpt:
      "A vibrant bowl packed with roasted sweet potato, quinoa, avocado, and a creamy tahini dressing.",
    category: "Bowls",
    cookTime: "25 min",
    prepTime: "15 min",
    servings: 2,
    rating: 4.9,
    tags: ["Gluten-Free", "High Protein"],
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop",
    ingredients: [
      "1 cup quinoa, rinsed",
      "1 medium sweet potato, cubed",
      "1 ripe avocado, sliced",
      "1 cup shredded red cabbage",
      "1 cup chickpeas, drained and rinsed",
      "1 cup shredded carrots",
      "1/2 cup edamame, shelled",
      "2 tbsp tahini",
      "1 tbsp lemon juice",
      "1 tbsp maple syrup",
      "1 tbsp olive oil",
      "Salt and pepper to taste",
      "Sesame seeds for garnish",
    ],
    instructions: [
      "Cook quinoa according to package directions. Fluff with a fork and set aside.",
      "Preheat oven to 400°F (200°C). Toss sweet potato cubes with olive oil, salt, and pepper. Roast for 20-25 minutes until tender and golden.",
      "While the sweet potato roasts, prepare the tahini dressing by whisking together tahini, lemon juice, maple syrup, and 2-3 tbsp warm water until smooth.",
      "Warm the chickpeas in a small pan with a pinch of cumin and smoked paprika for 3-4 minutes.",
      "Divide quinoa between two bowls. Arrange sweet potato, avocado, red cabbage, carrots, chickpeas, and edamame in sections over the quinoa.",
      "Drizzle generously with tahini dressing and sprinkle with sesame seeds. Serve immediately.",
    ],
  },
  {
    slug: "avocado-chickpea-toast",
    title: "Avocado & Chickpea Toast",
    excerpt:
      "Crispy sourdough topped with smashed chickpeas, ripe avocado, cherry tomatoes, and a squeeze of lemon.",
    category: "Breakfast",
    cookTime: "10 min",
    prepTime: "5 min",
    servings: 2,
    rating: 4.7,
    tags: ["Quick", "High Fiber"],
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
    ingredients: [
      "4 slices sourdough bread",
      "1 can (400g) chickpeas, drained",
      "2 ripe avocados",
      "1 cup cherry tomatoes, halved",
      "1 lemon, juiced",
      "2 tbsp olive oil",
      "1 tsp chili flakes",
      "Fresh cilantro or parsley",
      "Salt and pepper to taste",
      "Everything bagel seasoning (optional)",
    ],
    instructions: [
      "Toast the sourdough slices until golden and crispy.",
      "In a bowl, roughly mash the chickpeas with a fork, leaving some chunks for texture. Mix in half the lemon juice, 1 tbsp olive oil, salt, and pepper.",
      "In another bowl, mash the avocados with the remaining lemon juice, salt, and pepper.",
      "Spread a thick layer of mashed avocado on each toast slice, then top with the chickpea mixture.",
      "Arrange halved cherry tomatoes on top. Drizzle with remaining olive oil and sprinkle with chili flakes.",
      "Garnish with fresh herbs and everything bagel seasoning if desired. Serve right away.",
    ],
  },
  {
    slug: "thai-peanut-noodles",
    title: "Thai Peanut Noodles",
    excerpt:
      "Silky rice noodles tossed in a spicy peanut sauce with crunchy vegetables and fresh herbs.",
    category: "Mains",
    cookTime: "30 min",
    prepTime: "15 min",
    servings: 4,
    rating: 4.8,
    tags: ["Nut-Free Option", "Meal Prep"],
    image:
      "https://images.unsplash.com/photo-1540914124281-342587941389?w=600&h=400&fit=crop",
    ingredients: [
      "250g rice noodles",
      "1/3 cup peanut butter (or sunflower seed butter for nut-free)",
      "3 tbsp soy sauce or tamari",
      "2 tbsp rice vinegar",
      "1 tbsp sriracha",
      "1 tbsp maple syrup",
      "1 tbsp sesame oil",
      "1 red bell pepper, julienned",
      "1 cup shredded carrots",
      "1 cup snap peas, halved",
      "3 green onions, sliced",
      "Fresh cilantro and crushed peanuts for garnish",
      "Lime wedges for serving",
    ],
    instructions: [
      "Cook rice noodles according to package directions. Drain, rinse with cold water, and set aside.",
      "Whisk together peanut butter, soy sauce, rice vinegar, sriracha, maple syrup, sesame oil, and 3 tbsp warm water until smooth and creamy.",
      "In a large wok or skillet, heat a splash of oil over high heat. Stir-fry bell pepper, carrots, and snap peas for 3-4 minutes until crisp-tender.",
      "Add the cooked noodles to the wok and pour the peanut sauce over everything. Toss well to coat evenly.",
      "Remove from heat. Add sliced green onions and toss once more.",
      "Serve in bowls topped with fresh cilantro, crushed peanuts, and a squeeze of lime.",
    ],
  },
  {
    slug: "mediterranean-stuffed-peppers",
    title: "Mediterranean Stuffed Peppers",
    excerpt:
      "Bell peppers filled with herbed rice, sun-dried tomatoes, olives, and a balsamic glaze.",
    category: "Mains",
    cookTime: "45 min",
    prepTime: "20 min",
    servings: 4,
    rating: 4.6,
    tags: ["Gluten-Free", "Whole Food"],
    image:
      "https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?w=600&h=400&fit=crop",
    ingredients: [
      "4 large bell peppers, tops cut off and seeds removed",
      "1 1/2 cups cooked brown rice or quinoa",
      "1/2 cup sun-dried tomatoes, chopped",
      "1/3 cup kalamata olives, sliced",
      "1 can (400g) white beans, drained",
      "2 cups fresh spinach, chopped",
      "3 cloves garlic, minced",
      "1 tsp dried oregano",
      "1 tsp dried basil",
      "2 tbsp balsamic glaze",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
      "Fresh basil leaves for garnish",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Place hollow peppers upright in a baking dish.",
      "Heat olive oil in a skillet. Sauté garlic for 1 minute until fragrant, then add spinach and cook until wilted.",
      "In a large bowl, combine cooked rice, sautéed spinach, sun-dried tomatoes, olives, white beans, oregano, basil, salt, and pepper. Mix well.",
      "Stuff each pepper generously with the rice mixture, pressing down gently. Drizzle tops with a little olive oil.",
      "Cover the baking dish with foil and bake for 30 minutes. Remove foil and bake another 10-15 minutes until peppers are tender.",
      "Drizzle with balsamic glaze and garnish with fresh basil leaves before serving.",
    ],
  },
  {
    slug: "mango-coconut-chia-pudding",
    title: "Mango Coconut Chia Pudding",
    excerpt:
      "Creamy overnight chia pudding layered with fresh mango and toasted coconut flakes.",
    category: "Breakfast",
    cookTime: "5 min + overnight",
    prepTime: "10 min",
    servings: 2,
    rating: 4.8,
    tags: ["No-Cook", "Meal Prep"],
    image:
      "https://images.unsplash.com/photo-1511690743698-d9d18f7e20f1?w=600&h=400&fit=crop",
    ingredients: [
      "1/3 cup chia seeds",
      "1 cup coconut milk (full fat for creamiest result)",
      "1/2 cup oat milk or almond milk",
      "2 tbsp maple syrup",
      "1 tsp vanilla extract",
      "1 large ripe mango, diced",
      "3 tbsp toasted coconut flakes",
      "Fresh mint leaves (optional)",
      "Passion fruit pulp (optional topping)",
    ],
    instructions: [
      "In a jar or bowl, combine chia seeds, coconut milk, oat milk, maple syrup, and vanilla extract. Stir well.",
      "Cover and refrigerate for at least 4 hours or overnight. The chia seeds will absorb the liquid and form a thick pudding.",
      "In the morning, give the pudding a good stir. If it's too thick, add a splash more milk.",
      "Divide between two bowls or jars. Layer with diced mango.",
      "Top with toasted coconut flakes, fresh mint, and a drizzle of passion fruit pulp if desired.",
      "Enjoy cold — this keeps well in the fridge for up to 3 days, making it a perfect meal prep breakfast.",
    ],
  },
  {
    slug: "roasted-cauliflower-tacos",
    title: "Roasted Cauliflower Tacos",
    excerpt:
      "Spiced cauliflower florets on warm tortillas with pickled onion, cilantro lime crema, and fresh salsa.",
    category: "Mains",
    cookTime: "35 min",
    prepTime: "20 min",
    servings: 4,
    rating: 4.9,
    tags: ["Crowd Pleaser", "Gluten-Free Option"],
    image:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop",
    ingredients: [
      "1 large head cauliflower, cut into small florets",
      "2 tbsp olive oil",
      "1 tsp smoked paprika",
      "1 tsp cumin",
      "1/2 tsp chili powder",
      "8 small corn or flour tortillas",
      "1 red onion, thinly sliced",
      "1/4 cup apple cider vinegar",
      "1 tbsp sugar",
      "1/2 cup cashews, soaked 2 hours",
      "1 lime, juiced",
      "1/4 cup fresh cilantro",
      "1 avocado, sliced",
      "Fresh salsa or pico de gallo",
    ],
    instructions: [
      "Quick-pickle the onions: combine sliced red onion, apple cider vinegar, sugar, and a pinch of salt in a jar. Set aside for at least 20 minutes.",
      "Preheat oven to 425°F (220°C). Toss cauliflower florets with olive oil, smoked paprika, cumin, chili powder, salt, and pepper. Spread on a baking sheet.",
      "Roast for 25-30 minutes, flipping halfway, until edges are golden and crispy.",
      "Make the cilantro lime crema: blend soaked cashews, lime juice, cilantro, 3 tbsp water, and a pinch of salt until completely smooth.",
      "Warm tortillas in a dry skillet or directly over a gas flame for 15-20 seconds per side.",
      "Assemble tacos: fill each tortilla with roasted cauliflower, pickled onions, avocado slices, a drizzle of cilantro lime crema, and fresh salsa.",
    ],
  },
  {
    slug: "green-goddess-salad",
    title: "Green Goddess Salad",
    excerpt:
      "Crunchy romaine, cucumber, and edamame with a creamy herbed green goddess dressing.",
    category: "Salads",
    cookTime: "15 min",
    prepTime: "15 min",
    servings: 2,
    rating: 4.5,
    tags: ["Raw", "High Protein"],
    image:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&h=400&fit=crop",
    ingredients: [
      "1 large head romaine lettuce, chopped",
      "1 cucumber, diced",
      "1 cup edamame, shelled",
      "1 avocado",
      "1/2 cup fresh basil leaves",
      "1/4 cup fresh chives",
      "2 tbsp lemon juice",
      "1 clove garlic",
      "3 tbsp olive oil",
      "2 tbsp nutritional yeast",
      "Salt and pepper to taste",
      "Hemp seeds and sunflower seeds for topping",
    ],
    instructions: [
      "Prepare the green goddess dressing: blend avocado, basil, chives, lemon juice, garlic, olive oil, nutritional yeast, 2 tbsp water, salt, and pepper until silky smooth.",
      "In a large bowl, combine chopped romaine, diced cucumber, and edamame.",
      "Pour the green goddess dressing over the salad and toss until everything is evenly coated.",
      "Divide between serving bowls and top with hemp seeds and sunflower seeds.",
      "Serve immediately for the best crunch. The dressing can be made ahead and stored in the fridge for up to 3 days.",
    ],
  },
  {
    slug: "sweet-potato-black-bean-chili",
    title: "Sweet Potato & Black Bean Chili",
    excerpt:
      "A hearty, smoky chili loaded with tender sweet potatoes, black beans, corn, and warming spices.",
    category: "Soups",
    cookTime: "40 min",
    prepTime: "15 min",
    servings: 6,
    rating: 4.7,
    tags: ["Comfort Food", "Freezer-Friendly"],
    image:
      "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&h=400&fit=crop",
    ingredients: [
      "2 medium sweet potatoes, peeled and cubed",
      "2 cans (400g each) black beans, drained",
      "1 can (400g) diced tomatoes",
      "1 cup corn kernels (fresh or frozen)",
      "1 large onion, diced",
      "3 cloves garlic, minced",
      "1 jalapeño, seeded and diced",
      "2 tbsp chili powder",
      "1 tsp cumin",
      "1 tsp smoked paprika",
      "2 cups vegetable broth",
      "2 tbsp olive oil",
      "Fresh cilantro, avocado, and lime for serving",
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat. Sauté diced onion for 4-5 minutes until softened. Add garlic and jalapeño and cook 1 minute more.",
      "Stir in chili powder, cumin, and smoked paprika. Toast the spices for 30 seconds until fragrant.",
      "Add sweet potato cubes, black beans, diced tomatoes, corn, and vegetable broth. Stir to combine.",
      "Bring to a boil, then reduce heat to low. Cover and simmer for 25-30 minutes until sweet potatoes are fork-tender.",
      "Season with salt and pepper to taste. For a thicker chili, mash some of the sweet potato against the side of the pot.",
      "Serve hot in bowls topped with fresh cilantro, diced avocado, and a squeeze of lime. Freezes beautifully for up to 3 months.",
    ],
  },
  {
    slug: "berry-acai-smoothie-bowl",
    title: "Berry Acai Smoothie Bowl",
    excerpt:
      "Thick and creamy acai blended with mixed berries, topped with granola, banana, and hemp seeds.",
    category: "Breakfast",
    cookTime: "10 min",
    prepTime: "5 min",
    servings: 1,
    rating: 4.8,
    tags: ["Quick", "Superfood"],
    image:
      "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600&h=400&fit=crop",
    ingredients: [
      "2 frozen acai packets (100g each)",
      "1 cup frozen mixed berries",
      "1 frozen banana",
      "1/3 cup oat milk or almond milk",
      "1 tbsp almond butter",
      "Toppings: granola, sliced banana, fresh berries",
      "Hemp seeds and chia seeds",
      "Drizzle of honey or maple syrup",
      "Coconut flakes (optional)",
    ],
    instructions: [
      "Run the frozen acai packets under warm water for a few seconds to loosen them slightly.",
      "Add acai, frozen berries, frozen banana, oat milk, and almond butter to a high-speed blender.",
      "Blend on low, using the tamper to push ingredients down. The mixture should be very thick — thicker than a regular smoothie. Add milk only 1 tbsp at a time if needed.",
      "Pour the thick smoothie into a bowl and smooth the surface with a spoon.",
      "Arrange toppings in rows: sliced banana, fresh berries, granola, hemp seeds, chia seeds, and coconut flakes.",
      "Drizzle with honey or maple syrup and serve immediately before it melts.",
    ],
  },
];
